name: Build and Deploy User Service

on:
  push:
    paths:
      - 'user-service/**'       # Trigger when files in api-gateway folder change
      - 'helmcharts/user-service/**'       
env:
  AWS_REGION : "ap-south-1"
  
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: "Configure AWS Credentials" 
        uses: aws-actions/configure-aws-credentials@v4.0.2   
        with:
          role-to-assume: arn:aws:iam::654654187843:role/github-oidc
          role-session-name: gh-oidc
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image 
        env: 
          IMAGE_TAG: "${{ secrets.USER_ECR_REPOSITORY }}:user-service-${{ github.sha }}" 
        run: |
          docker build -t $IMAGE_TAG -f user-service/Dockerfile user-service

      - name: Push Docker image to ECR 
        env: 
          IMAGE_TAG: "${{ secrets.USER_ECR_REPOSITORY }}:user-service-${{ github.sha }}" 
        run: | 
          docker push $IMAGE_TAG

      # - name: Update kubeconfig
      #   run: |
      #     aws eks update-kubeconfig --name demo-cluster --region ${{ secrets.AWS_REGION }}

      # - name: Check Kubernetes config
      #   run: |
      #     cat ~/.kube/config
      #     kubectl cluster-info

      # - name: Deploy User Service with Helm
      #   run: |
      #     helm upgrade --install user-service helmcharts/user-service \
      #       --set image.tag=user-service-${{ github.sha }}
